site_name:  Eclipse Common Build Infrastructure 
site_url: https://eclipse-cbi-mkdocs/
theme:
  name: material
  logo: assets/CBI.png
  language: en 

extra_css:
  - assets/extra.css

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/eclipse-cbi

copyright: Copyright © Eclipse Foundation, Inc. All Rights Reserved.

plugins:
  - search:
      lang: en
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
      pipeline:
        - stemmer
        - stopWordFilter
        - trimmer
  - tags
  - multirepo:
      cleanup: true
      keep_docs_dir: true
      # repos:
      #   - section: Core 
      #     section_path: JIRO 
      #     import_url: 'https://github.com/eclipse-cbi/jiro.git?branch=master&edit_uri=master&docs_dir=/*'
      #   - section: Agent 
      #     section_path: JIRO 
      #     import_url: 'https://github.com/eclipse-cbi/jiro-agents.git?branch=master&edit_uri=master&docs_dir=/*'
      #   - section: Controller 
      #     section_path: JIRO 
      #     import_url: 'https://github.com/eclipse-cbi/jiro-masters.git?branch=master&edit_uri=master&docs_dir=/*'
      #   - section: Dockerfile 
      #     section_path: JIRO 
      #     import_url: 'https://github.com/eclipse-cbi/dockerfiles.git?branch=master&edit_uri=master&docs_dir=/README.md'
          
      #   - section: Gitab Runner Service 
      #     import_url: 'https://gitlab.eclipse.org/eclipsefdn/it/releng/gitlab-runner-service/gitlab-runner-service-documentation.git?branch=main&edit_uri=main&docs_dir=/*'

      #   - section: Documentation
      #     section_path: Chat Service 
      #     import_url: 'https://gitlab.eclipse.org/eclipsefdn/it/releng/chat-service/chat-service-website.git?branch=main&edit_uri=main&docs_dir=content/*'
      #   - section: Provisionner
      #     section_path: Chat Service 
      #     import_url: 'https://gitlab.eclipse.org/eclipsefdn/it/releng/chat-service/chat-service-provisioner.git?branch=main&edit_uri=main&docs_dir=/*'
      #   - section: Synapse
      #     section_path: Chat Service 
      #     import_url: 'https://gitlab.eclipse.org/eclipsefdn/it/releng/chat-service/synapse.git?branch=main&edit_uri=main&docs_dir=/*'
      #   - section: Elementweb
      #     section_path: Chat Service 
      #     import_url: 'https://gitlab.eclipse.org/eclipsefdn/it/releng/chat-service/element-web.git?branch=main&edit_uri=main&docs_dir=/*'
      #   - section: Sync tools
      #     section_path: Chat Service 
      #     import_url: 'https://gitlab.eclipse.org/eclipsefdn/it/releng/chat-service/chat-service-sync.git?branch=main&edit_uri=main&docs_dir=/*'

      #   - section: MACOS Notarization Service 
      #     import_url: 'https://github.com/eclipse-cbi/macos-notarization-service.git?branch=main&edit_uri=main&docs_dir=/README.md'

      nav_repos:
        - name: JIRO Core 
          import_url: 'https://github.com/eclipse-cbi/jiro.git?branch=master'
          imports: ['*.md']
        - name: JIRO Agent 
          import_url: 'https://github.com/eclipse-cbi/jiro-agents.git?branch=master'
          imports: ['*.md']
        - name: JIRO Controller 
          import_url: 'https://github.com/eclipse-cbi/jiro-masters.git?branch=master'
          imports: ['*.md']

        - name: CBI Dockerfile 
          import_url: 'https://github.com/eclipse-cbi/dockerfiles.git?branch=master'
          imports: ['README.md']
        
        - name: Gitlab Runner Service 
          import_url: 'https://gitlab.eclipse.org/eclipsefdn/it/releng/gitlab-runner-service/gitlab-runner-service-documentation.git?branch=main&edit_uri=main'
          imports: ['readme.md']
        - name: Gitlab Runner Template 
          import_url: 'https://gitlab.eclipse.org/eclipsefdn/it/releng/gitlab-runner-service/gitlab-ci-templates.git?branch=main&edit_uri=main'
          imports: ['README.md']
        - name: Gitlab Runner as code 
          import_url: 'https://gitlab.eclipse.org/eclipsefdn/it/releng/gitlab-runner-service/gitlab-runner-as-code?branch=main&edit_uri=main'
          imports: ['README.md']

        - name: Chat Service Documentation
          import_url: 'https://gitlab.eclipse.org/eclipsefdn/it/releng/chat-service/chat-service-website.git?branch=main&edit_uri=main'
          imports: ['*.md']
        - name: Chat Service  Provisionner
          import_url: 'https://gitlab.eclipse.org/eclipsefdn/it/releng/chat-service/chat-service-provisioner.git?branch=main&edit_uri=main'
          imports: ['*.md']
        - name: Chat Service  Synapse
          import_url: 'https://gitlab.eclipse.org/eclipsefdn/it/releng/chat-service/synapse.git?branch=main&edit_uri=main'
          imports: ['*.md']
        - name: Chat Service  Elementweb
          import_url: 'https://gitlab.eclipse.org/eclipsefdn/it/releng/chat-service/element-web.git?branch=main&edit_uri=main'
          imports: ['*.md']
        - name: Chat Service  Sync tools
          import_url: 'https://gitlab.eclipse.org/eclipsefdn/it/releng/chat-service/chat-service-sync.git?branch=main&edit_uri=main'
          imports: ['*.md']

        - name: Develocity
          import_url: 'https://gitlab.eclipse.org/eclipsefdn/it/releng/develocity/develocity-documentation?branch=main&edit_uri=main'
          imports: ['*.md']

        - name: Signing Services
          import_url: 'https://github.com/eclipse-cbi/org.eclipse.cbi.git?branch=main'
          imports: ['*.md']

        - name: Best Practices
          import_url: 'https://github.com/eclipse-cbi/best-practices.git?branch=main'
          imports: ['*.md']

        - name: MACOS Notarization Service 
          import_url: 'https://github.com/eclipse-cbi/macos-notarization-service.git?branch=main'
          imports: ['README.md']

#       nav_repos:
#         - name: Jiro
#           import_url: 'https://github.com/eclipse-cbi/jiro?branch=master'
#           imports: [/README.md]
#         - name: Gitlab-Runner-Service
#           import_url: 'https://gitlab.eclipse.org/eclipsefdn/it/releng/gitlab-runner-service/gitlab-runner-service-documentation.git?branch=main&edit_uri=main'
#           imports: [/readme.md]
#         # - name: Chat-Service
#         #   import_url: 'https://gitlab.eclipse.org/eclipsefdn/it/releng/chat-service/chat-service-website.git?branch=main&edit_uri=main&docs_dir=content/*'


nav:
  - CBI Documentation: https://github.com/eclipse-cbi/cbi/wiki
  - JIRO:
      - Wiki: https://github.com/eclipse-cbi/jiro/wiki
      - Core: jiro-core/index.html
      - Agent: jiro-agent/index.html
      - Controller: jiro-controller/index.html
  - Container management: cbi-dockerfile/index.html
  - Gitlab Runner Service: 
      - Documentation: gitlab-runner-service/readme/index.html
      - Gitlab Runner Template: gitlab-runner-template/index.html
      - Grac!: gitlab-runner-as-code/index.html
  - Chat Service:
      - Let's chat: https://chat.eclipse.org
      - Documentation: https://chat.eclipse.org/docs/
      - Matrix at Eclipse: chat-service-documentation/content/_index/index.html
      - Getting Started: chat-service-documentation/content/getting-started/_index/index.html
      - FAQ: chat-service-documentation/content/faq/_index/index.html
      - Rooms/Spaces: chat-service-documentation/content/rooms/_index/index.html
      - Provisionner: chat-service-provisionner/readme/index.html
      - Synapse: chat-service-synapse/readme/index.html
      - Elementweb: chat-service-elementweb/readme/index.html
      - Sync Tools: chat-service-sync-tools/readme/index.html
  - Develocity: develocity/readme/index.html
  - Otterdog: https://otterdog.readthedocs.io/en/latest/
  - Signing Service: 
      - CBI Maven plugins: signing-services/index.html
      - CLI: signing-services/cli-tools/signing/jar/index.html
      - Maven plugins: signing-services/maven-plugins/index.html
      - Macosx webservice: signing-services/webservice/signing/macosx/index.html
  - MACOS Notarization Service: macos-notarization-service/index.html
  - Best Practices: 
      - Common Best Practices: best-practices/index.html
      - Software Supply Chain: best-practices/software-supply-chain/osssc-best-practices/index.html
  - Helpdesk: 
      - Open an issue: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/new
      - SLO: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/wikis/IT-Service-Level-Objectives
  - Sharing secrets: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/wikis/Sharing-secrets
  - Security Handbook: https://eclipse-csi.github.io/security-handbook/index.html
  - Service links: 
      - ci.eclipse.org: 'https://ci.eclipse.org/'
      - develocity-staging: 'https://develocity-staging.eclipse.org'
      - chat.eclipse.org: 'https://chat.eclipse.org'
      - otterdog: 'https://otterdog.eclipse.org'
      - repo.eclipse.org: 'https://repo.eclipse.org'
      - cbi-dev mailing-list: https://accounts.eclipse.org/mailing-list/cbi-dev


# nav:
#   - JIRO: 
#     - Core: JIRO/core/index.html
  #   - Agent: '!import https://github.com/eclipse-cbi/jiro-agents.git?branch=master&docs_dir=/*&multi_docs=False&config=mkdocs.yml&keep_docs_dir=True'
  #   - Controller: '!import https://github.com/eclipse-cbi/jiro-masters.git?branch=master&docs_dir=/*&multi_docs=False&config=mkdocs.yml&keep_docs_dir=True'
  #   - Dockerfile: '!import https://github.com/eclipse-cbi/dockerfiles.git?branch=master&docs_dir=/README.md&multi_docs=False&config=mkdocs.yml&keep_docs_dir=True'
  #   - GitLab Runner Service: '!import https://gitlab.eclipse.org/eclipsefdn/it/releng/gitlab-runner-service/gitlab-runner-service-documentation.git?branch=main&docs_dir=/*&multi_docs=False&config=mkdocs.yml&keep_docs_dir=True'
  # - Chat Service:
  #   - Documentation: '!import https://gitlab.eclipse.org/eclipsefdn/it/releng/chat-service/chat-service-website.git?branch=main&docs_dir=content/*&multi_docs=False&config=mkdocs.yml&keep_docs_dir=True'
  #   - Provisioner: '!import https://gitlab.eclipse.org/eclipsefdn/it/releng/chat-service/chat-service-provisioner.git?branch=main&docs_dir=/*&multi_docs=False&config=mkdocs.yml&keep_docs_dir=True'
  #   - Synapse: '!import https://gitlab.eclipse.org/eclipsefdn/it/releng/chat-service/synapse.git?branch=main&docs_dir=/*&multi_docs=False&config=mkdocs.yml&keep_docs_dir=True'
  #   - ElementWeb: '!import https://gitlab.eclipse.org/eclipsefdn/it/releng/chat-service/element-web.git?branch=main&docs_dir=/*&multi_docs=False&config=mkdocs.yml&keep_docs_dir=True'
  #   - Sync Tools: '!import https://gitlab.eclipse.org/eclipsefdn/it/releng/chat-service/chat-service-sync.git?branch=main&docs_dir=/*&multi_docs=False&config=mkdocs.yml&keep_docs_dir=True'
  # - MacOS Notarization Service: '!import https://github.com/eclipse-cbi/macos-notarization-service.git?branch=main&docs_dir=/README.md&multi_docs=False&config=mkdocs.yml&keep_docs_dir=True'

  # - ci.eclipse.org: 'https://ci.eclipse.org/'
# nav:
#   - Home: index.md
#   - JIRO:
#       - Home: jiro/README.md
#   - Gitlab Runner Service:
#       - HOME: gitlab-runner-service/readme.md
#   - Chat Service:


# plugins:
#   - search
#   - multirepo:
#       # (optional) tells multirepo to cleanup the temporary directory after site is built.
#       cleanup: false
#       nav_repos:
#         - name: backstage
#           import_url: https://github.com/backstage/backstage
#           # forward slash is needed in '/README.md' so that only the README.md in the root
#           # directory is imported and not all README.md files.
#           imports: [
#             docs/publishing.md, docs/integrations/index.md, /README.md,
#             # asset files needed
#             docs/assets/*
#             ]
#         - name: fast-api
#           import_url: https://github.com/tiangolo/fastapi
#           imports: [docs/en/docs/index.md]

# nav:
#   - Backstage:
#       - Home: backstage/README.md
#       - Integration: backstage/docs/integrations/index.md
#       - Publishing: backstage/docs/publishing.md